### ISSUE TITLE
About super_res_sample

### ISSUE THREAD

**Issue by zxt-triumph** [jychoi118/ilvr_adm#16]
What is the base_samples?

**Comment by jychoi118** [comment]
It is directory to the low-resolution input images.

**Comment by zxt-triumph** [comment]
When I specify the directory, I get the following error:
+ python scripts/super_res_sample.py --attention_resolutions 16 --class_cond False --diffusion_steps 1000 --dropout 0.0 --large_size 256 --small_size 64 --learn_sigma False --noise_schedule linear --num_channels 128 --num_head_channels 4 --num_res_blocks 2 --resblock_updown False --use_fp16 False --use_scale_shift_norm False --timestep_respacing 100 --model_path ./logs/res_256/ema_0.9999_002000.pt --base_samples ./datasets/test/
Logging to ./logs/res_256/
creating model...
loading data...
creating samples...
Traceback (most recent call last):
  File "/home/ztf/project/zxt/Code/Diffusion Models/Noise2Noise/scripts/super_res_sample.py", line 119, in <module>
    main()
  File "/home/ztf/project/zxt/Code/Diffusion Models/Noise2Noise/scripts/super_res_sample.py", line 47, in main
    model_kwargs = next(data)
  File "/home/ztf/project/zxt/Code/Diffusion Models/Noise2Noise/scripts/super_res_sample.py", line 78, in load_data_for_worker
    with bf.BlobFile(base_samples, "rb") as f:
  File "/home/ztf/anaconda3/envs/vgan/lib/python3.9/site-packages/blobfile/_ops.py", line 356, in BlobFile
    return default_context.BlobFile(
  File "/home/ztf/anaconda3/envs/vgan/lib/python3.9/site-packages/blobfile/_context.py", line 859, in BlobFile
    raise IsADirectoryError(f"Is a directory: '{path}'")
IsADirectoryError: Is a directory: './datasets/test/'

**Comment by jychoi118** [comment]
Oh, in this script, base_sample is .npz file of low-resolution images.
You can modify the script by using data loader from super_res_train.py.
For example,
![image](https://user-images.githubusercontent.com/36615789/180678339-333b012d-e6c0-48b8-8656-1eddace0f976.png)
![image](https://user-images.githubusercontent.com/36615789/180678398-dc2a5b50-dcea-40df-aa21-901eb3875f74.png)
